kind: pipeline
name: default
steps:
    - name: test
      image: "golang:alpine"
      commands:
          - apk add --no-cache gcc ca-certificates git make
          - make
          - bash <(curl -s https://codecov.io/bash)
