kind: pipeline
name: default
steps:
    - name: test
      image: "golang:alpine"
      commands:
          - apk add --no-cache build-base ca-certificates git
          - make test
          - bash <(curl -s https://codecov.io/bash)
