kind: pipeline
name: default
steps:
    - name: test
      image: "golang:alpine"
      commands:
          - go test -race -short -coverprofile=coverage.txt -covermode=atomic ./...
          - bash <(curl -s https://codecov.io/bash)
